Home2
IvanMaximenko2004/EasyIT-course pull request #1
Opened 2020-08-31 17:22 UTC by IvanMaximenko2004

2020-08-31 21:13 UTC, bloodybaker approved these changes
Nice

2020-08-31 21:14 UTC, bloodybaker requested changes
Исправь конфликт в ветках

2020-09-01 18:15 UTC, IvanMaximenko2004 commented
> Исправь конфликт в ветках


Это как?

2020-09-01 18:18 UTC, bloodybaker commented
> > Исправь конфликт в ветках
> 
> Это как?

Я уже исправил. Можно мержить (Merge pull request)

2020-09-01 18:19 UTC, merged

2020-09-01 18:20 UTC, IvanMaximenko2004 commented
> > > Исправь конфликт в ветках
> > 
> > 
> > Это как?
> 
> Я уже исправил. Можно мержить (Merge pull request)

А, а я уже что-то не так сделал, да?

2020-09-01 18:21 UTC, IvanMaximenko2004 commented
Я походу мержнул и закрыл его

2020-09-01 18:23 UTC, bloodybaker commented
> Я походу мержнул и закрыл его

Да, всё ок

2020-09-01 18:28 UTC, IvanMaximenko2004 commented
> > Я походу мержнул и закрыл его
> 
> Да, всё ок

Может наперёд всё-таки кинь мне что-то, потому что мне уже нехер делать, слишком мало ты задаешь)

2020-09-01 18:29 UTC, IvanMaximenko2004 commented
Я если чё почитаю как делать, если чёт что я не знаю, попробую разобрать

2020-09-01 18:34 UTC, bloodybaker commented
> > > Я походу мержнул и закрыл его
> > 
> > 
> > Да, всё ок
> 
> Может наперёд всё-таки кинь мне что-то, потому что мне уже нехер делать, слишком мало ты задаешь)

Окей

2020-09-02 11:12 UTC, IvanMaximenko2004 commented
Так чё там, ты тут или в телеге домаху кинешь?

2020-09-02 18:02 UTC, bloodybaker commented
> Так чё там, ты тут или в телеге домаху кинешь?

в телеге